[package]
name = "seda-mainchain"
version = "0.1.0"
edition = "2021"
resolver = "2"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-contract-standards = { workspace = true }
near-sdk = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true, features = ["std"] }
